# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False, verbose_name='部门编号')),
                ('name', models.CharField(max_length=20, verbose_name='部门名称')),
                ('location', models.CharField(max_length=10, verbose_name='部门所在地')),
                ('excellent', models.BooleanField(default=0, verbose_name='是否优秀')),
            ],
            options={
                'db_table': 'tb_dept',
            },
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('job', models.CharField(max_length=10)),
                ('sal', models.DecimalField(decimal_places=2, max_digits=7)),
                ('comm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='application.Dept')),
                ('mgr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.Emp')),
            ],
            options={
                'db_table': 'tb_emp',
            },
        ),
    ]
